import Image from "next/image";

export default function Home() {
  return (
    <div className=" flex items-center justify-center flex-col -mt-14">
      <Image
         className="w-24 h-auto"
        src="/storage/images/logos/dostv.png"
        alt="DOSTV Logo"
        width={100}
        height={100}
        priority
      />
      <div className="text-white">
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1><h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>
        <h1>Ho</h1>

      </div>
    </div>
  );
}
